apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: voting-app
    service: postgres-service
spec:
  selector:
    app: voting-app
    name: postgres-pod
  ports:
    - port: 5432
      targetPort: 5432
