apiVersion: v1 
kind: Pod

metadata:
  name: redis-pod
  labels:
    app: voting-app
    name: redis-pod 


spec:
  containers:
    - name: redis
      image: redis:alpine
      ports:
        - containerPort: 6379
      