apiVersion: v1

kind: Service 

metadata:
  name: result-app-service
  labels:
    app: voting-app
    name: result-app-service

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009
  selector:
    app: voting-app
    name: result-app