apiVersion: v1

kind: Pod


metadata:
  name: voiting-app-pod
  labels:
    app: voting-app
    name: voiting-app-pod

spec:
  containers:
    - name: voiting-app
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"