apiVersion: v1  

kind: Service 

metadata:
  name: voting-app-service
  labels:
    app: voting-app
    name: voting-app-service
  
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      NodePort: 30008
  selector:
    app: voting-app
    name: voting-app