apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    app: voting-app
    name: worker-app-pod
spec:
  containers:
  - name: worker-app
    image: kodekloud/examplevotingapp_worker:v1
    env:
    - name: DB_HOST
      value: "postgres-service"  # Example hostname
    - name: DB_PORT
      value: "5432"
    - name: DB_NAME
      value: "voting_app"
    - name: DB_USER
      value: "postgres"
    - name: DB_PASSWORD
      value: "postgres"