apiVersion: v1  
kind: Service

metadata:
  name: worker-app-service
  labels:
    app: voting-app 
    name: worker-app-service

spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: voting-app
    name: worker-app